# Generated by Django 3.1.3 on 2020-12-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarpenterForeman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(default='Carpenter - Foreman', max_length=255)),
                ('employee_numbers', models.IntegerField()),
                ('regular_hours', models.IntegerField()),
                ('premium_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarpenterJourneyamn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(default='Carpenter - Journeyman', max_length=255)),
                ('employee_numbers', models.IntegerField()),
                ('regular_hours', models.IntegerField()),
                ('premium_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('contractor_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laborer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(default='Laborer', max_length=255)),
                ('employee_numbers', models.IntegerField()),
                ('regular_hours', models.IntegerField()),
                ('premium_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(default='Supervisor', max_length=255)),
                ('employee_numbers', models.IntegerField()),
                ('regular_hours', models.IntegerField()),
                ('premium_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaperForeman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(default='Taper - Foreman', max_length=255)),
                ('employee_numbers', models.IntegerField()),
                ('regular_hours', models.IntegerField()),
                ('premium_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaperJourneyman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(default='Taper - Journeyman', max_length=255)),
                ('employee_numbers', models.IntegerField()),
                ('regular_hours', models.IntegerField()),
                ('premium_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('work_performed', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carpenterforeman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workorder_app.carpenterforeman')),
                ('carpenterjourneyamn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workorder_app.carpenterjourneyamn')),
                ('jobname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workorder_app.jobname')),
                ('laborer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workorder_app.laborer')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workorder_app.supervisor')),
                ('taperforeman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workorder_app.taperforeman')),
                ('taperjourneyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workorder_app.taperjourneyman')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workorder_app.workorder')),
            ],
        ),
    ]
