# Generated by Django 3.1.3 on 2020-12-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='signature_1',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
