# Generated by Django 3.1.3 on 2020-12-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0002_workorder_signature_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobname',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
