# Generated by Django 3.1.3 on 2020-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_app', '0003_auto_20201207_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='signator_1',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='signator_2',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='signature_2',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpenterforeman',
            name='employee_numbers',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='carpenterforeman',
            name='premium_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='carpenterforeman',
            name='regular_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='carpenterjourneyamn',
            name='employee_numbers',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='carpenterjourneyamn',
            name='premium_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='carpenterjourneyamn',
            name='regular_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='laborer',
            name='employee_numbers',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='laborer',
            name='premium_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='laborer',
            name='regular_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='employee_numbers',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='premium_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='regular_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='taperforeman',
            name='employee_numbers',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='taperforeman',
            name='premium_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='taperforeman',
            name='regular_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='taperjourneyman',
            name='employee_numbers',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='taperjourneyman',
            name='premium_hours',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='taperjourneyman',
            name='regular_hours',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
